version: '3'

services:
  data:
    container_name: data
    image: data
    build:
      context: ./
      dockerfile: ./data/Dockerfile
    networks:
      - app-network
    links:
      - "mongo"
  api:
    container_name: api
    image: api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    links:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    logging:
     driver: none
    networks:
      - app-network
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
