version: '3'

services:
#  data:
#    container_name: data
#    image: data
#    build: ./data
#    networks:
#      - app-network
#    links:
#      - "mongo"
  api:
    container_name: api
    image: api
    build: ./api
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    links:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    networks:
      - app-network
    logging:
      driver: none
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge